dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres 
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: dbt_schema 
      port: 5432
